name: sashimi
description: A sprite stacking framework build on top of the Flame Engine.
repository: https://github.com/wolfenrain/sashimi
version: 0.1.0-dev.3

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flame: ^1.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_test: ^1.9.1
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
